### ISSUE TITLE
Claiming venue without providing email/website/phone is possible

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleApp-iOS#267] opened 2013-08-17 12:51 UTC
see unverified venue The mad bishop: http://shnergle-admin.azurewebsites.net/?controller=venues&venue-search=&staff-search=&type-search=to-veri

**Comment by krzd** [comment] 2013-08-17 13:04
The creator and claimer used 1.0, did we fix it in there or later?

**Comment by uansett** [comment] 2013-08-17 13:06
Don't think we changed it after 1.0 intentionally. So whatever is
wrong in 1.0 is probably in 1.2

Stian

**Comment by krzd** [comment] 2013-08-17 13:15
Does not seem that we fixed it after 1.0 (https://github.com/shnergle/ShnergleApp-iOS/compare/v1.0-1...v1.2), but cannot reproduce either in master (asks me to fill in all fields).

**Comment by uansett** [comment] 2013-08-17 13:18
Filling in fields, going back to add venue, then back and wipe the
fields? I don't think he used spaces did he? Hmm.. In any case we
should reset the venue and email him. Was probably a joke though

**Comment by krzd** [comment] 2013-08-17 13:19
Ah, I tried claiming it as a seperate step.

**Comment by uansett** [comment] 2013-08-17 19:35
Reproduce:
Tap claim venue
Tap back
Tap claim venue
Tap done
This is v1.1

**Comment by krzd** [comment] 2013-08-17 20:05
Cannot reproduce like that on master=v1.2, can you confirm? If so, I guess this can be closed.

**Comment by uansett** [comment] 2013-08-17 20:54
No I just reproduced it on 1.2 as well. Just go back and then try
again pressing done. It will send off the request and put you as
manager (unverified) im afraid

**Comment by krzd** [comment] 2013-08-17 21:10
When creating or claiming? Seriously can't reproduce whilst claiming.

**Comment by uansett** [comment] 2013-08-17 21:24
Yeah claiming. Put some soul into it Adam! You'll make it ;) go in,
don't edit, press claim again and then done

**Comment by krzd** [comment] 2013-08-17 21:38
I have put my soul and body into it. I did it like a hundred times, I get the message 'Please fill in all fields'.

**Comment by krzd** [comment] 2013-08-19 14:08
Only possible on iOS 6, not on ios 7. I will add additonal checks which might address this issue, but as there is no consistent pattern as to when it happens, this is a wontfix, if it is not fixed by my next commit. Especially since from iOS 7 it does not matter anymore.

**Closed as completed** 2013-08-19 14:09 UTC
Labels: bug, required
